# 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/account?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password:
# mybatis 配置
mybatis:
  mapper-locations: "classpath*:/mapper/**/*Mapper.xml"
  type-aliases-package: com.code.boot.mybatis.v1.model
